INSERT INTO director (fullName)
VALUES ('Квентин Тарантино'),
       ('Стивен Спилберг'),
       ('Альфред Хичкок'),
       ('Клинт Иствуд'),
       ('Люк Бессон'),
       ('Пол У. С. Андерсон'),
       ('Питер Фаррелли'),
       ('Светлана Баскова'),
       ('Майк Джадж'),
       ('Сильвестр Сталлоне'),
       ('Фрэнк Дарабонт'),
       ('Оливье Накаш'),
       ('Андрей Звягинцев'),
       ('Дэвид Йейтс'),
       ('Зак Снайдер'),
       ('Александр Ажа'),
       ('Джон М. Чу'),
       ('Джошуа Земан');


INSERT INTO movie (name, release_year, description, director_id)
VALUES ('Криминальное чтиво', 1994, 'Культовый фильм Тарантино',
        (select id from director where fullName like 'Квентин Тарантино')),
       ('Бешеные псы', 1992, 'Драма о грабителях и полиции',
        (select id from director where fullName like 'Квентин Тарантино')),
       ('Убить Билла', 2003, 'История о мести насильственной бывшей невесты',
        (select id from director where fullName like 'Квентин Тарантино')),
       ('Челюсти', 1975, 'Фильм ужасов про акулу',
        (select id from director where fullName like 'Стивен Спилберг')),
       ('Индиана Джонс: В поисках утраченного ковчега', 1981, 'Приключенческий фильм',
        (select id from director where fullName like 'Стивен Спилберг')),
       ('Список Шиндлера', 1993, 'Фильм о спасении евреев во время Холокоста',
        (select id from director where fullName like 'Стивен Спилберг')),
       ('Психо', 1960, 'Триллер о психопате-убийце',
        (select id from director where fullName like 'Альфред Хичкок')),
       ('Бесславные ублюдки', 2009, 'Фильм о группе американских солдат во время Второй мировой войны',
        (select id from director where fullName like 'Клинт Иствуд')),
       ('Без прощания', 1971, 'Драма о преступниках и охоте на них',
        (select id from director where fullName like 'Клинт Иствуд')),
       ('Пятый элемент', 1997, 'Научно-фантастический боевик',
        (select id from director where fullName like 'Люк Бессон')),
       ('Обитель зла', 2002, 'Фантастический хоррор',
        (select id from director where fullName like 'Пол У. С. Андерсон')),
       ('Неудержимые', 2010, 'Боевик о наемных убийцах',
        (select id from director where fullName like 'Сильвестр Сталлоне')),
       ('Зелёный слоник', 2003, 'Драма о жизни школьного учителя',
        (select id from director where fullName like 'Светлана Баскова')),
       ('Кремнивая долина', 2014, 'Комедийный сериал о высокотехнологичной индустрии',
        (select id from director where fullName like 'Майк Джадж')),
       ('Муви 43', 2013, 'Комедийный антологический фильм',
        (select id from director where fullName like 'Питер Фаррелли')),
       ('Зеленая миля', 1999, 'Фильм о чудесах, которые случаются в тюремном блоке смертников',
        (SELECT id FROM director WHERE fullName = 'Фрэнк Дарабонт')),
       ('1+1', 2011, 'Фильм о дружбе между богатым инвалидом и бедным иммигрантом',
        (SELECT id FROM director WHERE fullName = 'Оливье Накаш')),
       ('Левиафан', 2014, 'Фильм о борьбе простого человека с коррупцией и несправедливостью',
        (SELECT id FROM director WHERE fullName = 'Андрей Звягинцев')),
       ('Гарри Поттер и Принц-полукровка', 2009, 'Фильм о шестом годе обучения Гарри Поттера в школе магии',
        (SELECT id FROM director WHERE fullName = 'Дэвид Йейтс')),
       ('Рога', 2013, 'Фильм о парне, который обвиняется в убийстве своей девушки и начинает превращаться в дьявола',
        (SELECT id FROM director WHERE fullName = 'Александр Ажа')),
       ('Иллюзия обмана 2', 2016, 'Фильм о команде иллюзионистов, которые сражаются с тайным орденом',
        (SELECT id FROM director WHERE fullName = 'Джон М. Чу')),
       ('Левиафан: История одного кита', 2013, 'Документальный фильм о жизни и смерти самого большого кита в мире',
        (SELECT id FROM director WHERE fullName = 'Джошуа Земан')),
       ('Легенды ночных стражей', 2010, 'Мультфильм о совах-воителях, которые защищают свой мир от зла',
        (SELECT id FROM director WHERE fullName = 'Зак Снайдер'));

INSERT INTO cast_member (fullName)
VALUES ('Джон Траволта'),
       ('Сэмюэл Л. Джексон'),
       ('Ума Турман'),
       ('Брюс Уиллис'),
       ('Тим Рот'),
       ('Харви Кейтель'),
       ('Майкл Мэдсен'),
       ('Стив Бушеми'),
       ('Люси Лью'),
       ('Дэвид Кэррадайн'),
       ('Рой Шайдер'),
       ('Роберт Шоу'),
       ('Ричард Дрефусс'),
       ('Харрисон Форд'),
       ('Карен Аллен'),
       ('Лиам Нисон'),
       ('Бен Кинсли'),
       ('Рэйф Файнс'),
       ('Энтони Перкинс'),
       ('Джанет Ли'),
       ('Брэд Питт'),
       ('Майкл Фассбендер'),
       ('Кристоф Вальц'),
       ('Клинт Иствуд'),
       ('Мила Йовович'),
       ('Гари Олдман'),
       ('Мишель Родригес'),
       ('Джеймс Пьюрфой'),
       ('Джейсон Стэйтем'),
       ('Хью Джекман'),
       ('Кейт Уинслет'),
       ('Халли Берри'),
       ('Сергей Пахомов'),
       ('Владимир Епифанцев'),
       ('Алекс Маслаев'),
       ('Томас Миддлдитч'),
       ('Джош Бренер'),
       ('Мартин Старр'),
       ('Том Хэнкс'),
       ('Майкл Кларк Дункан'),
       ('Дэвид Морс'),
       ('Франсуа Клюзе'),
       ('Омар Си'),
       ('Анн Ле Ни'),
       ('Алексей Серебряков'),
       ('Елена Лядова'),
       ('Владимир Вдовиченков'),
       ('Дэниел Рэдклифф'),
       ('Эмма Уотсон'),
       ('Руперт Гринт'),
       ('Джун Темпл'),
       ('Макс Мингелла'),
       ('Марк Руффало'),
       ('Дэйв Франко'),
       ('Джесси Айзенберг'),
       ('Вуди Харрельсон'),
       ('Сара Пэлин'),
       ('Габриэль Старбак'),
       ('Хелен Миррен'),
       ('Джим Стёрджесс'),
       ('Эмили Барклай'),
       ('Райан Квантен');


INSERT INTO movie_cast_member (movie_id, cast_member_id, role)
VALUES ((select id from MOVIE where NAME like 'Криминальное чтиво'),
        (select id from CAST_MEMBER where FULLNAME like 'Джон Тр%'), 'Винсент Вега'),
       ((select id from MOVIE where NAME like 'Криминальное чтиво'),
        (select id from CAST_MEMBER where FULLNAME like 'Сэмюэл %'), 'Джулс Винфилд'),
       ((select id from MOVIE where NAME like 'Криминальное чтиво'),
        (select id from CAST_MEMBER where FULLNAME like 'Ума Тур%'), 'Миа Уоллес'),
       ((select id from MOVIE where NAME like 'Бешеные псы'),
        (select id from CAST_MEMBER where FULLNAME like 'Брюс Уи%'), 'Корбен Даллас'),
       ((select id from MOVIE where NAME like 'Бешеные псы'),
        (select id from CAST_MEMBER where FULLNAME like 'Тим Рот%'), 'Мистер Оранжевый'),
       ((select id from MOVIE where NAME like 'Бешеные псы'),
        (select id from CAST_MEMBER where FULLNAME like 'Харви К%'), 'Мистер Белый'),
       ((select id from MOVIE where NAME like 'Бешеные псы'),
        (select id from CAST_MEMBER where FULLNAME like 'Майкл М%'), 'Мистер Блонд'),
       ((select id from MOVIE where NAME like 'Убить Билла'),
        (select id from CAST_MEMBER where FULLNAME like 'Стив Бу%'), 'Мистер Розовый'),
       ((select id from MOVIE where NAME like 'Убить Билла'),
        (select id from CAST_MEMBER where FULLNAME like 'Люси Ль%'), 'О-Рен Ишии'),
       ((select id from MOVIE where NAME like 'Убить Билла'),
        (select id from CAST_MEMBER where FULLNAME like 'Дэвид К%'), 'Билл'),
       ((select id from MOVIE where NAME like 'Челюсти'),
        (select id from CAST_MEMBER where FULLNAME like 'Рой Шай%'), 'Мартин Броди'),
       ((select id from MOVIE where NAME like 'Челюсти'),
        (select id from CAST_MEMBER where FULLNAME like 'Роберт %'), 'Куинт'),
       ((select id from MOVIE where NAME like 'Челюсти'),
        (select id from CAST_MEMBER where FULLNAME like 'Ричард %'), 'Мэтт Хупер'),
       ((select id from MOVIE where NAME like 'Индиана Джонс: В поисках утраченного ковчега'),
        (select id from CAST_MEMBER where FULLNAME like 'Харрисо%'), 'Индиана Джонс'),
       ((select id from MOVIE where NAME like 'Индиана Джонс: В поисках утраченного ковчега'),
        (select id from CAST_MEMBER where FULLNAME like 'Карен А%'), 'Марион Рэйвенвуд'),
       ((select id from MOVIE where NAME like 'Список Шиндлера'),
        (select id from CAST_MEMBER where FULLNAME like 'Лиам Ни%'), 'Оскар Шиндлер'),
       ((select id from MOVIE where NAME like 'Список Шиндлера'),
        (select id from CAST_MEMBER where FULLNAME like 'Бен Кин%'), 'Ицхак Штерн'),
       ((select id from MOVIE where NAME like 'Список Шиндлера'),
        (select id from CAST_MEMBER where FULLNAME like 'Рэйф Фа%'), 'Амон Гет'),
       ((select id from MOVIE where NAME like 'Психо'),
        (select id from CAST_MEMBER where FULLNAME like 'Энтони %'), 'Норман Бейтс/мать'),
       ((select id from MOVIE where NAME like 'Психо'),
        (select id from CAST_MEMBER where FULLNAME like 'Джанет %'), 'Марион Крейн'),
       ((select id from MOVIE where NAME like 'Бесславные ублюдки'),
        (select id from CAST_MEMBER where FULLNAME like 'Брэд Пи%'), 'Альдо Рейн'),
       ((select id from MOVIE where NAME like 'Бесславные ублюдки'),
        (select id from CAST_MEMBER where FULLNAME like 'Майкл Ф%'), 'Арчи Хикокс'),
       ((select id from MOVIE where NAME like 'Бесславные ублюдки'),
        (select id from CAST_MEMBER where FULLNAME like 'Кристоф%'), 'Ганс Ланда'),
       ((select id from MOVIE where NAME like 'Без прощания'),
        (select id from CAST_MEMBER where FULLNAME like 'Клинт И%'), 'Инспектор "Грязный Гарри" Колби'),
       ((select id from MOVIE where NAME like 'Пятый элемент'),
        (select id from CAST_MEMBER where FULLNAME like 'Мила Йовович'), 'Лилу'),
       ((select id from MOVIE where NAME like 'Пятый элемент'),
        (select id from CAST_MEMBER where FULLNAME like 'Брюс Уиллис'), 'Мистер Чёрч'),
       ((select id from MOVIE where NAME like 'Пятый элемент'),
        (select id from CAST_MEMBER where FULLNAME like 'Гари Олдман'), 'Жан-Батист Эммануэль Зорг'),
       ((select id from MOVIE where NAME like 'Обитель зла'),
        (select id from CAST_MEMBER where FULLNAME like 'Мила Йовович'), 'Алиса'),
       ((select id from MOVIE where NAME like 'Обитель зла'),
        (select id from CAST_MEMBER where FULLNAME like 'Мишель Родригес'), 'Рейн Окампо'),
       ((select id from MOVIE where NAME like 'Обитель зла'),
        (select id from CAST_MEMBER where FULLNAME like 'Джеймс Пьюрфой'), 'Спенсер Паркинс'),
       ((select id from MOVIE where NAME like 'Неудержимые'),
        (select id from CAST_MEMBER where FULLNAME like 'Мила Йовович'), 'Кэтлин Сандерс'),
       ((select id from MOVIE where NAME like 'Неудержимые'),
        (select id from CAST_MEMBER where FULLNAME like 'Брюс Уиллис'), 'Бутч Кулидж'),
       ((select id from MOVIE where NAME like 'Неудержимые'),
        (select id from CAST_MEMBER where FULLNAME like 'Джейсон Стэйтем'), 'Ли Кристмас'),
       ((select id from MOVIE where NAME like 'Муви 43'),
        (select id from CAST_MEMBER where FULLNAME like 'Хью Джекман'), 'Дэвис'),
       ((select id from MOVIE where NAME like 'Муви 43'),
        (select id from CAST_MEMBER where FULLNAME like 'Кейт Уинслет'), 'Бет'),
       ((select id from MOVIE where NAME like 'Муви 43'),
        (select id from CAST_MEMBER where FULLNAME like 'Халли Берри'), 'Эми'),
       ((select id from MOVIE where NAME like 'Зелёный слоник'),
        (select id from CAST_MEMBER where FULLNAME like 'Сергей Пахомов'), 'Поехавший'),
       ((select id from MOVIE where NAME like 'Зелёный слоник'),
        (select id from CAST_MEMBER where FULLNAME like 'Владимир Епифанцев'), 'Братишка'),
       ((select id from MOVIE where NAME like 'Зелёный слоник'),
        (select id from CAST_MEMBER where FULLNAME like 'Алекс Маслаев'), 'Полковник'),
       ((select id from MOVIE where NAME like 'Кремнивая долина'),
        (select id from CAST_MEMBER where FULLNAME like 'Томас Миддлдитч'), 'Ричард Хендрикс'),
       ((select id from MOVIE where NAME like 'Кремнивая долина'),
        (select id from CAST_MEMBER where FULLNAME like 'Джош Бренер'), 'Нельсон «Башка» Бигетти'),
       ((select id from MOVIE where NAME like 'Кремнивая долина'),
        (select id from CAST_MEMBER where FULLNAME like 'Мартин Старр'), 'Гилфойл'),
       ((SELECT id FROM movie WHERE name = 'Зеленая миля'), (SELECT id FROM cast_member WHERE fullName = 'Том Хэнкс'),
        'Пол Эджкомб'),
       ((SELECT id FROM movie WHERE name = 'Зеленая миля'),
        (SELECT id FROM cast_member WHERE fullName = 'Майкл Кларк Дункан'), 'Джон Коффи'),
       ((SELECT id FROM movie WHERE name = 'Зеленая миля'), (SELECT id FROM cast_member WHERE fullName = 'Дэвид Морс'),
        'Брутус Хауэлл'),
       ((SELECT id FROM movie WHERE name = '1+1'), (SELECT id FROM cast_member WHERE fullName = 'Франсуа Клюзе'),
        'Филипп'),
       ((SELECT id FROM movie WHERE name = '1+1'), (SELECT id FROM cast_member WHERE fullName = 'Омар Си'), 'Дрисс'),
       ((SELECT id FROM movie WHERE name = '1+1'), (SELECT id FROM cast_member WHERE fullName = 'Анн Ле Ни'), 'Магали'),
       ((SELECT id FROM movie WHERE name = 'Левиафан'),
        (SELECT id FROM cast_member WHERE fullName = 'Алексей Серебряков'), 'Николай Сергеевич'),
       ((SELECT id FROM movie WHERE name = 'Левиафан'), (SELECT id FROM cast_member WHERE fullName = 'Елена Лядова'),
        'Лилия Сергеевна'),
       ((SELECT id FROM movie WHERE name = 'Левиафан'),
        (SELECT id FROM cast_member WHERE fullName = 'Владимир Вдовиченков'), 'Дмитрий Северянов'),
       ((SELECT id FROM movie WHERE name = 'Гарри Поттер и Принц-полукровка'),
        (SELECT id FROM cast_member WHERE fullName = 'Дэниел Рэдклифф'), 'Гарри Поттер'),
       ((SELECT id FROM movie WHERE name = 'Гарри Поттер и Принц-полукровка'),
        (SELECT id FROM cast_member WHERE fullName = 'Эмма Уотсон'), 'Гермиона Грейнджер'),
       ((SELECT id FROM movie WHERE name = 'Гарри Поттер и Принц-полукровка'),
        (SELECT id FROM cast_member WHERE fullName = 'Руперт Гринт'), 'Рон Уизли'),
       ((SELECT id FROM movie WHERE name = 'Рога'), (SELECT id FROM cast_member WHERE fullName = 'Дэниел Рэдклифф'),
        'Игг Перриш'),
       ((SELECT id FROM movie WHERE name = 'Рога'), (SELECT id FROM cast_member WHERE fullName = 'Джун Темпл'),
        'Меррин Уильямс'),
       ((SELECT id FROM movie WHERE name = 'Рога'), (SELECT id FROM cast_member WHERE fullName = 'Макс Мингелла'),
        'Ли Турнер'),
       ((SELECT id FROM movie WHERE name = 'Иллюзия обмана 2'),
        (SELECT id FROM cast_member WHERE fullName = 'Марк Руффало'), 'Дилан Родс'),
       ((SELECT id FROM movie WHERE name = 'Иллюзия обмана 2'),
        (SELECT id FROM cast_member WHERE fullName = 'Дэйв Франко'), 'Джек Уайлдер'),
       ((SELECT id FROM movie WHERE name = 'Иллюзия обмана 2'),
        (SELECT id FROM cast_member WHERE fullName = 'Джесси Айзенберг'), 'Дэниел Атлас'),
       ((SELECT id FROM movie WHERE name = 'Иллюзия обмана 2'),
        (SELECT id FROM cast_member WHERE fullName = 'Вуди Харрельсон'), 'Мерритт МакКинни / Чейз МакКинни'),
       ((SELECT id FROM movie WHERE name = 'Левиафан: История одного кита'),
        (SELECT id FROM cast_member WHERE fullName = 'Сара Пэлин'), 'Она же'),
       ((SELECT id FROM movie WHERE name = 'Левиафан: История одного кита'),
        (SELECT id FROM cast_member WHERE fullName = 'Габриэль Старбак'), 'Она же'),
       ((SELECT id FROM movie WHERE name = 'Легенды ночных стражей'),
        (SELECT id FROM cast_member WHERE fullName = 'Хелен Миррен'), 'Ниобе, озвучка'),
       ((SELECT id FROM movie WHERE name = 'Легенды ночных стражей'),
        (SELECT id FROM cast_member WHERE fullName = 'Джим Стёрджесс'), 'Сорен, озвучка'),
       ((SELECT id FROM movie WHERE name = 'Легенды ночных стражей'),
        (SELECT id FROM cast_member WHERE fullName = 'Эмили Барклай'), 'Гилфи, озвучка'),
       ((SELECT id FROM movie WHERE name = 'Легенды ночных стражей'),
        (SELECT id FROM cast_member WHERE fullName = 'Райан Квантен'), 'Клудд, озвучка');