databaseChangeLog:
  - changeSet:
      id: edit tables for spring security
      author: Aleksei
      changes:
        - dropForeignKeyConstraint:
            baseTableName: roles
            constraintName: fk_user_email
        - createTable:
            tableName: roles_authorities
            columns:
              - column:
                  name: role_id
                  type: long
                  constraints:
                    nullable: false
                    primaryKey: true
                    foreignKeyName: fk_role_id
                    references: roles(id)
              - column:
                  name: authority_id
                  type: long
                  constraints:
                    nullable: false
                    primaryKey: true
                    foreignKeyName: fk_authority_id
                    references: authorities(id)
        - dropColumn:
            tableName: roles
            columnName: authority_id
        - dropColumn:
            tableName: roles
            columnName: user_email
        - addColumn:
            tableName: roles
            columns:
              - column:
                  name: role
                  type: varchar(50)
        - createTable:
            tableName: users_roles
            columns:
              - column:
                  name: user_email
                  type: varchar(50)
                  constraints:
                    nullable: false
                    primaryKey: true
                    foreignKeyName: fk_user_email_id
                    references: user_table(email)
              - column:
                  name: role_id
                  type: long
                  constraints:
                    nullable: false
                    primaryKey: true
                    foreignKeyName: fk_role_id_to_user
                    references: roles(id)